version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eecs647-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tv03k4eipc5o"
s3_prefix = "eecs647-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
